# BSUP
[start]
id = 0
tid = 0
næste = [1]

[Overordnet_specifikation]
id = 1
tid = 6
næste = [2,3,4,5]

[Specifikation_A]
id = 2
tid = 9
næste = [6]

[Specifikation_B]
id = 3
tid = 7
næste = [7]

[Specifikation_C]
id = 4
tid = 11
næste = [8]

[Specifikation_D]
id = 5
tid = 6
næste = [8]

[Godkend_Specifikation_A]
id = 6
tid = 2
næste = [9, 22]

[Godkend_Specifikation_B]
id = 7
tid = 2
næste = [10, 22]

[Godkend_Specifikation_C_og_D]
id = 8
tid = 3
næste = [11, 12, 22]

[Design_A]
id = 9
tid = 8
næste = [13]

[Design_B]
id = 10
tid = 5
næste = [14]

[Design_C]
id = 11
tid = 17
næste = [15]

[Design_D]
id = 12
tid = 11
næste = [15]

[Godkend_design_A]
id = 13
tid = 2
næste = [16]

[Godkend_design_B]
id = 14
tid = 2
næste = [17]

[Godkend_design_C+D]
id = 15
tid = 3
næste = [18, 19]

[Kod_og_test_A]
id = 16
tid = 16
næste = [20]

[Kod_og_test_B]
id = 17
tid = 11
næste = [20]

[Kod_og_test_C]
id = 18
tid = 16
næste = [20]

[Kod_og_test_D]
id = 19
tid = 14
næste = [20]

[Samlet_test]
id = 20
tid = 6
næste = [21]

[I_gang_sættelse]
id = 21
tid = 6
næste = [24]

[Udarbejdelse_af_vejledelse]
id = 22
tid = 7
næste = [23]

[Brugeruddannelse]
id = 23
tid = 6
næste = [24]

[slut]
id = 24
tid = 0
næste = []